name: Flutter CI/CD Pipeline

on:
  push:
    branches:
      - main  # Runs workflow on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'  # Specify Flutter version explicitly
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Run Flutter Tests
        run: flutter test

      - name: Build APK
        run: flutter build apk --release

      - name: Build Web
        run: flutter build web --release

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Flutter-APK
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Deploy to GitHub Pages
        if: success()
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "your-username"
          git checkout --orphan gh-pages
          git rm -rf .
          cp -r build/web/* .
          git add .
          git commit -m "Deploy web version"
          git push origin gh-pages --force
